### ISSUE TITLE
TASK Add Asset content

### ISSUE THREAD

**Issue by thejhh** [hyperifyio/rune#12]
### Goal 

Enable asset files.

### Input file as html

```html
<Asset name="softwarePackage">data:application/zip;base64,xxxxxx</Asset>
```

### Input file as yml

```yml
- type: Asset
  name: "softwarePackage"
  body: "data:application/zip;base64,xxxxxx"
```

### End result JSON

```json
[
  {
    "type": "Asset",
    "name": "softwarePackage",
    "body": "data:application/zip;base64,xxxxxx"
  }
]
```
