### ISSUE TITLE
TASK Implement component support

### ISSUE THREAD

**Issue by thejhh** [hyperifyio/rune#5]
### Goal

Reusable components

### Example YAML

```yaml
- type: "Component"
  name: "UsageCard"
  body:
  - type: div
    classes:
    - w-full
    - m-1
    - p-0
    body:
    - type: "UnfoldableCard"
      title: "usageCard.title"
      initialOpen: False
      body:
      - usageCard.content
```

### Example HTML

```html
<Component name="UsageCard">
  <div class="w-full m-1 p-0">
    <UnfoldableCard title="usageCard.title"
                    initialOpen="False"
    >usageCard.content</UnfoldableCard>
  </div>
</Component>
```
