### ISSUE TITLE
TASK Implement HTML input support

### ISSUE THREAD

**Issue by thejhh** [hyperifyio/rune#6]
Support for using HTML files instead of YAML, like this:

```html
<View name="HelloWorld">
  <div class="hello-world-container">
    <div class="header">
      <h1>app.title</h1>
    </div>
    <div class="content">
      <p>app.content</p>
    </div>
    <div class="footer">
      <button class="start-button" 
              onClick='{"navigate":"/app/start"}'
      >app.startButton.label</button>
    </div>
  </div>
</View>
```

instead of:

```yaml
- type: "View"
  name: "HelloWorld"
  body:
  - type: div
    classes:
    - "hello-world-container"
    body:
    - type: div
      classes:
      - "header"
      body:
      - type: h1
        body:
        - "app.title"
    - type: div
      classes:
      - "content"
      body:
      - type: p
        body:
        - "app.content"
    - type: div
      classes:
      - "footer"
      body:
      - type: button
        onClick:
          navigate: "/app/start"
        classes:
        - "start-button"
        body:
        - "app.startButton.label"
```
